const statusCode = {
  // 1xx Informational
  100: "Continue",
  101: "Switching Protocols",
  102: "Processing (WebDAV)",
  103: "Early Hints",

  // 2xx Success
  200: "OK",
  201: "Created",
  202: "Accepted",
  203: "Non-Authoritative Information",
  204: "No Content",
  205: "Reset Content",
  206: "Partial Content",
  207: "Multi-Status (WebDAV)",
  208: "Already Reported (WebDAV)",
  226: "IM Used",

  // 3xx Redirection
  300: "Multiple Choices",
  301: "Moved Permanently",
  302: "Found",
  303: "See Other",
  304: "Not Modified",
  305: "Use Proxy (Deprecated)",
  306: "Switch Proxy (Unused)",
  307: "Temporary Redirect",
  308: "Permanent Redirect",

  // 4xx Client errors
  400: "Bad Request",
  401: "Unauthorized",
  402: "Payment Required",
  403: "Forbidden",
  404: "Not Found",
  405: "Method Not Allowed",
  406: "Not Acceptable",
  407: "Proxy Authentication Required",
  408: "Request Timeout",
  409: "Conflict",
  410: "Gone",
  411: "Length Required",
  412: "Precondition Failed",
  413: "Payload Too Large",
  414: "URI Too Long",
  415: "Unsupported Media Type",
  416: "Range Not Satisfiable",
  417: "Expectation Failed",
  418: "I'm a Teapot",
  419: "Page Expired (Laravel Framework)",
  420: "Enhance Your Calm (Twitter)",
  421: "Misdirected Request",
  422: "Unprocessable Entity (WebDAV)",
  423: "Locked (WebDAV)",
  424: "Failed Dependency (WebDAV)",
  425: "Too Early",
  426: "Upgrade Required",
  428: "Precondition Required",
  429: "Too Many Requests",
  430: "Request Header Fields Too Large (Shopify)",
  431: "Request Header Fields Too Large",
  440: "Login Timeout (IIS)",
  444: "No Response (Nginx)",
  449: "Retry With (IIS)",
  450: "Blocked by Windows Parental Controls",
  451: "Unavailable For Legal Reasons",
  460: "Client Closed Connection (AWS ELB)",
  463: "Unauthorized (AWS ELB)",

  // Cloudflare 4xx
  494: "Request Header Too Large (Nginx)",
  495: "SSL Certificate Error (Nginx)",
  496: "SSL Certificate Required (Nginx)",
  497: "HTTP Request Sent to HTTPS Port (Nginx)",
  498: "Invalid Token (Esri/Cloudflare)",
  499: "Client Closed Request (Nginx/Cloudflare)",

  // 5xx Server errors
  500: "Internal Server Error",
  501: "Not Implemented",
  502: "Bad Gateway",
  503: "Service Unavailable",
  504: "Gateway Timeout",
  505: "HTTP Version Not Supported",
  506: "Variant Also Negotiates",
  507: "Insufficient Storage (WebDAV)",
  508: "Loop Detected (WebDAV)",
  509: "Bandwidth Limit Exceeded (Apache/cPanel)",
  510: "Not Extended",
  511: "Network Authentication Required",

  // Unofficial Microsoft/IIS
  520: "Unknown Error (Cloudflare)",
  521: "Web Server Is Down (Cloudflare)",
  522: "Connection Timed Out (Cloudflare)",
  523: "Origin Is Unreachable (Cloudflare)",
  524: "A Timeout Occurred (Cloudflare)",
  525: "SSL Handshake Failed (Cloudflare)",
  526: "Invalid SSL Certificate (Cloudflare)",
  527: "Railgun Error (Cloudflare)",
  529: "Site is Overloaded (Qualys)",
  530: "Site Frozen (Cloudflare/Shopify)",
  540: "Temporarily Disabled (AWS AppStream)",
  561: "Unauthorized (AWS ELB)",

  // AWS & Custom
  598: "Network Read Timeout Error (Unknown)",
  599: "Network Connect Timeout Error (Unknown)",
};

export default statusCode;
